### ISSUE TITLE
Feature - Reverse Transliteration

### ISSUE THREAD

**Issue by hetarth18** [praatibhsurana/Hinglish_Hindi_WSD#1]
Is there any plan for including Hindi-Hinglish transliteration (the reverse of what the library has currently)?

**Comment by praatibhsurana** [comment]
Hey, as of now we don't have any plans for the same. To my knowledge, I also think that datasets for reverse transliteration are extremely scarce. I wasn't able to find anything relevant on the internet either after skimming briefly.
